version: '3'
services:
  bdws_start-spring-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: start-spring-api
    image: bdws/start-spring-api
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx256m -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=devdocker
  db:
    container_name: start-spring-db
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=startSpringDb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=freeaccess
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 5
#      links:
#        - node-exporter:node-exporter


#  node-exporter:
#    image: prom/node-exporter:latest
#    network_mode: host
#    container_name: monitoring_node_exporter
#    restart: unless-stopped
#    expose:
#      - 9100


  prometheus:
    image: prom/prometheus:v2.35.0
    network_mode: host
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"

  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    network_mode: host
    container_name: grafana
    restart: unless-stopped
    user: root
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      # Enabled for logging
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug

volumes:
  dbdata:
    driver: local