server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - start-spring-api
    labels:
      application: start-spring-api
      __path__: /var/log/start-spring-api/*log
  pipeline_stages:
    - regex:
        expression: ".*(?P<log_level>INFO|ERROR|DEBUG|WARN).*"
    - labels:
        log_level: